stages:
  - code quality
  - testing

variables:
  POSTGRES_DB: market
  POSTGRES_USER: skillbox
  POSTGRES_PASSWORD: secret
  POSTGRES_HOST_AUTH_METHOD: trust

services:
  - name: redis:latest
    alias: broker
  - name: postgres:latest
    alias: db

default:
  image: python:3.10.6
  tags:
    - students
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - pip install -r requirements/dev.txt

flake8:
  stage: code quality
  script:
    - flake8 market

linter:
  stage: code quality
  script:
    - pylint --rcfile=.pylintrc market/*

test:
  stage: testing
  when: always
  variables:
    #
  script:
    - echo "DATABASE_URL = $DATABASE_URL" >> .env
    - echo "REDIS_URL = $REDIS_URL" >> .env
    - echo "STRIPE_PUBLISHABLE_KEY = $STRIPE_PUBLISHABLE_KEY" >> .env
    - echo "STRIPE_SECRET_KEY = $STRIPE_SECRET_KEY" >> .env
    - echo "STRIPE_WEBHOOK_KEY = $STRIPE_WEBHOOK_KEY" >> .env
    - echo "EMAIL_HOST_USER = $EMAIL_HOST_USER" >> .env
    - echo "EMAIL_HOST_PASSWORD = $EMAIL_HOST_PASSWORD" >> .env
    - cd market
    - python manage.py makemigrations
    - python manage.py test
